name: rl-stack
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip:
    - tensorflow<2.11
    - tensorflow-probability=0.18.0
    - keras
    - gym
    - numpy
    - matplotlib
    - wandb
    - pandas